@baseUrl = https://api.calorieninjas.com/v1
@apiKey = my_api_key

GET {{baseUrl}}/nutrition?query=100g chicken breast and 200g apples
X-Api-Key: {{apiKey}}

###

GET {{baseUrl}}/nutrition?query=chicken
X-Api-Key: {{apiKey}}

###

### '+' jel nem jó! Üres listát ad vissza!
GET {{baseUrl}}/nutrition?query=chicken+egg
X-Api-Key: {{apiKey}}

###

### '%20' jó!!!
GET {{baseUrl}}/nutrition?query=chicken%20apple
X-Api-Key: {{apiKey}}

###