GET localhost:8080/coupons

###

PUT localhost:8080/coupons/PREMIUM1/use/68

###

GET localhost:8080/coupons/validate/PREMIUM1

###

GET localhost:8080/coupons/validate/PREMIUM7

###

GET localhost:8080/coupons/validate/PREMIUM10

###

GET localhost:8080/coupons/validate/premium1

###

GET localhost:8080/coupons/validate/premium7

###

GET localhost:8080/coupons/validate/premium10

###

GET localhost:8080/coupons/validate/PREmium1

###

GET localhost:8080/coupons/validate/preMIUM7

###

GET localhost:8080/coupons/validate/PRemiUM10

###

GET localhost:8080/coupons/validate/NOTREALCODE