
GET localhost:8080/foods

###

POST localhost:8080/foods
Content-Type: application/json

{
  "name" : "Banana",
  "kcalAndNutrients" : {
    "kcal": 100.0,
    "fat": 1.0,
    "carb": 20.0,
    "protein": 1.0
  }
}

###

POST localhost:8080/foods
Content-Type: application/json

{
  "name": "Apple",
  "kcalAndNutrients": {
    "kcal": 52.0,
    "fat": 0.2,
    "carb": 14.0,
    "protein": 0.3
  }
}

###

PUT localhost:8080/foods/2
Content-Type: application/json

{
  "name": "New Apple",
  "kcalAndNutrients": {
    "kcal": 100.0,
    "fat": 100.0,
    "carb": 100.0,
    "protein": 100.0
  }
}

###

GET localhost:8080/foods

###

###Mindig legyen kikommentelve, ha nem használjuk, mert a PUT lefutása helyett ez fut le!!!
###DELETE localhost:8080/foods/1

###

GET localhost:8080/foods/2

###

