GET localhost:8080/measurementUnits/1

###

GET localhost:8080/measurementUnits/1/2

###

POST localhost:8080/measurementUnits/1
Content-Type: application/json

{
  "measurementUnitName" : "Fél kiló",
  "measurementUnitInGrams": 500
}

###

POST localhost:8080/measurementUnits/1
Content-Type: application/json

{
  "measurementUnitName" : "Mínusz kiló",
  "measurementUnitInGrams": -100
}

###

PUT localhost:8080/measurementUnits/1/2
Content-Type: application/json

{
  "measurementUnitName" : "Fél kiló",
  "measurementUnitInGrams": 500
}

###

PUT localhost:8080/measurementUnits/1
Content-Type: application/json

{
  "measurementUnitName" : "Fél kiló fele",
  "measurementUnitInGrams": 250
}

###

###DELETE localhost:8080/measurementUnits/2

